name: Run Python Tests

on:
  push: # Run the workflow on every push
    branches:
      - main  # Replace with the branch you want to monitor
  pull_request: # Run the workflow on pull requests to monitored branches

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository code
    - name: Check out code
      uses: actions/checkout@v2

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Specify the Python version you want to use

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Ensure you have a requirements.txt in the root directory

    # Step 4: Run tests
    - name: Run tests
      run: pytest test/test_training_pipeline.py
